const actionTypes = {
  profile: {
    FETCH_REQUEST: 'FETCH_REQUEST',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_AUTHOR_SUCCESS: 'FETCH_AUTHOR_SUCCESS',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    UPDATE_AVATAR_SUCCESS: 'UPDATE_AVATAR_SUCCESS',
    FETCH_FAILURE: 'FETCH_FAILURE',
    UPDATE_AFTER_BLOG_DELETION: 'UPDATE_AFTER_BLOG_DELETION',
  },
  author: {
    FETCH_REQUEST: 'FETCH_REQUEST',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_FAILURE: 'FETCH_FAILURE',
  },
  blog: {
    FETCH_REQUEST: 'FETCH_REQUEST',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_SINGLE_SUCCESS: 'FETCH_SINGLE_SUCCESS',
    CREATE_SUCCESS: 'CREATE_SUCCESS',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    DELETE_SUCCESS: 'DELETE_SUCCESS',
    FETCH_FAILURE: 'FETCH_FAILURE',
    RESET_BLOG: 'RESET_BLOG',
  },
};

export { actionTypes };
