const actionTypes = {
  profile: {
    FETCH_REQUEST: 'FETCH_REQUEST',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    UPDATE_AVATAR_SUCCESS: 'UPDATE_AVATAR_SUCCESS',
    FETCH_FAILURE: 'FETCH_FAILURE',
  },
  blog: {
    FETCH_REQUEST: 'FETCH_REQUEST',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    LIKE_SUCCESS: 'LIKE_SUCCESS',
    COMMENT_SUCCESS: 'COMMENT_SUCCESS',
    DELETE_SUCCESS: 'DELETE_SUCCESS',
    FETCH_FAILURE: 'FETCH_FAILURE',
  },
};

export { actionTypes };
